config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'
  resources :foundations
  resources :donations
  resources :events
  resources :menus
  resources :welcome
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/donation.rb
class Donation < ApplicationRecord
    validates :cuenta, presence: true, uniqueness:true, length: {minimum: 6}
    validates :banco, presence: true, length: {maximum: 60}
    validates :detalle, presence: true

end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/foundation.rb
class Foundation < ApplicationRecord
    validates :nombre, presence: true, uniqueness:true, length: {minimum: 10}
    validates :resumen, presence: true, length: {maximum: 60}
    validates :objeto, presence: true
    validates :telefono, presence: true, length: {minimum: 7}
    validates :sitio_web, presence: true, length: {maximum: 60}

end

app/models/menu.rb
class Menu < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    

end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController

     # Presentar lista general de fundaciones
  def index
    @Donation = Donation.all
  end
  # Presentar un articulo especifico
  def show
    @Donation = Donation.find(params[:id])
  end

  #Crear un articulo
  def new
    @Donation = Donation.new
   end

   def create
    @Donation = Donation.new(cuenta:params[:donation][:cuenta],banco:params[:donation][:banco],detalle:params[:donation][:detalle])

    if @Donation.save
        redirect_to @Donation
    else
        render :new
    end
  end

  #Eliminar un articulo
  def destroy
    @Donation = Donation.find(params[:id])
    @Donation.destroy
  redirect_to donations_path
  end

  #Editar un articulo
  def edit 
    @Donation = Donation.find(params[:id])
    end
    
    def update
      @Donation = Donation.find(params[:id])
        if @Donation.update(donation_params)
          redirect_to @Donation
        else
         render 'edit'
        end
    end

    private
    def donation_params
      params.require(:donation).permit(:cuenta, :banco, :detalle)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    # Presentar lista general de fundaciones
  def index
    @Event = Event.all
  end
  # Presentar un articulo especifico
  def show
    @Event = Event.find(params[:id])
  end

    #Crear un articulo
    def new
        @Event = Event.new
       end
    
       def create
        @Event = Event.new(nombre:params[:event][:nombre],lugar:params[:event][:lugar],fecha:params[:event][:fecha],participantes:params[:event][:participantes])
    
        if @Event.save
            redirect_to @Event
        else
            render :new
        end
      end

       #Eliminar un articulo
  def destroy
    @Event = Event.find(params[:id])
    @Event.destroy
  redirect_to events_path
  end
    
   #Editar un articulo
   def edit 
    @Event = Event.find(params[:id])
    end
    
    def update
      @Event = Event.find(params[:id])
        if @Event.update(event_params)
          redirect_to @Event
        else
         render 'edit'
        end
    end

    private
    def event_params
      params.require(:event).permit(:nombre, :lugar, :fecha, :participantes)
    end
end

app/controllers/foundations_controller.rb
class FoundationsController < ApplicationController
      # Presentar lista general de fundaciones
  def index
    @Foundation = Foundation.all
  end
  # Presentar un articulo especifico
  def show
    @Foundation = Foundation.find(params[:id])
  end
 
   #Crear un articulo
   def new
    @Foundation = Foundation.new
   end

   def create
    @Foundation = Foundation.new(nombre:params[:foundation][:nombre],resumen:params[:foundation][:resumen],objeto:params[:foundation][:objeto],telefono:params[:foundation][:telefono],sitio_web:params[:foundation][:sitio_web])

    if @Foundation.save
        redirect_to @Foundation
    else
        render :new
    end
  end

  #Eliminar un articulo
  def destroy
    @Foundation = Foundation.find(params[:id])
    @Foundation.destroy
  redirect_to foundations_path
  end

   #Editar un articulo
   def edit 
    @Foundation = Foundation.find(params[:id])
    end
    
    def update
      @Foundation = Foundation.find(params[:id])
        if @Foundation.update(foundation_params)
          redirect_to @Foundation
        else
         render 'edit'
        end
    end

    private
    def foundation_params
      params.require(:foundation).permit(:nombre, :resumen, :objeto, :telefono, :sitio_web)
    end
   

end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
     # Presentar lista general de fundaciones
  def index
    @Menu = Menu.all
  end
  # Presentar un articulo especifico
  def show
    @Menu = Menu.find(params[:id])
  end
 #Crear un articulo
 def new
    @Menu = Menu.new
   end

   def create
    @Menu = Menu.new(nombre:params[:menu][:nombre],enlace:params[:menu][:enlace])

    if @Menu.save
        redirect_to @Menu
    else
        render :new
    end
  end

  #Eliminar un articulo
  def destroy
    @Menu = Menu.find(params[:id])
    @Menu.destroy
  redirect_to menus_path
  end

  #Editar un articulo
  def edit 
    @Menu = Menu.find(params[:id])
    end
    
    def update
      @Menu = Menu.find(params[:id])
        if @Menu.update(menu_params)
          redirect_to @Menu
        else
         render 'edit'
        end
    end

    private
    def menu_params
      params.require(:menu).permit(:nombre, :enlace)
    end
   
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/foundations_helper.rb
module FoundationsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/donations/_form.html.erb
<div style=width:80%;margin:0 auto; class="container" >


<% name ||="Crear" %>
<h1> <%=name%> Donacion </h1>


<% @Donation.errors.full_messages.each do |error| %>
    <p><%= error %></p>
    <%end%>





<%= form_for(@Donation) do |f| %>
<%= f.number_field :cuenta, placeholder:"Numero de cuenta" %>
<%= f.text_field :banco, placeholder:"Corporacion bancaria" %>
<%= f.text_area :detalle, placeholder:"Información adicional a presentar" %>



<%= f.submit "Guardar" %>

    <%end%>

    </div>

app/views/donations/edit.html.erb
<div style=width:80%;margin:0 auto;>

    

<%=  render 'form', name:"Editar" %>

   </div>

app/views/donations/index.html.erb
<table class="striped">
<thead>
  <tr>
      <th>Cuenta</th>
      <th>Banco</th>
      <th>Información adicional</th>
      <th colspan="2" >Accion</th>
  </tr>
</thead>

<tbody>
  <tr>
  <% @Donation.each do |donacion| %>
    <td><%= donacion.cuenta %></td>
    <td><%= donacion.banco %></td>
    <td><%= donacion.detalle %></td>
    <td><%= link_to 'Editar', edit_donation_path(donacion) %></td>
    <td><%= link_to "Eliminar", donacion, method: :delete, data: { confirm: 'Esta seguro?' }%></td>
    </tr>
    <% end %>
  
  
</tbody>
</table>

app/views/donations/new.html.erb
<div style=width:80%;margin:0 auto;>

    

<%=  render 'form', name:"Crear" %>

   </div>

app/views/donations/show.html.erb
    <h3> <%= @Donation.cuenta %></h3>
    <p><%= @Donation.banco %></p>
    <p><%= @Donation.detalle %></p>

    <br>

app/views/events/_form.html.erb
<div style=width:80%;margin:0 auto; class="container" >


<% name ||="Crear" %>
<h1> <%=name%> Eventos </h1>



<% @Event.errors.full_messages.each do |error| %>
    <p><%= error %></p>
    <%end%>


<%= form_for(@Event) do |f| %>
<%= f.text_field :nombre, placeholder:"Nombre del Evento" %>
<%= f.text_field :lugar, placeholder:"Sitio o Lugar del evento" %>
<%= f.date_field :fecha, placeholder:"Fecha del Evento" %>
<%= f.text_area :participantes, placeholder:"Participantes, grupos de interes" %>

<%= f.submit "Guardar" %>

    <%end%>

    </div>

app/views/events/edit.html.erb
<div style=width:80%;margin:0 auto;>

    

<%=  render 'form', name:"Editar" %>

   </div>

app/views/events/index.html.erb
<table class="striped">
<thead>
  <tr>
      <th>Nombre del Evento</th>
      <th>Lugar - Sitio</th>
      <th>Fecha</th>
      <th>Participantes o grupos de interes</th>
      <th colspan="2" >Accion</th>
  </tr>
</thead>

<tbody>
  <tr>
  <% @Event.each do |event| %>
    <td><%= event.nombre %></td>
    <td><%= event.lugar %></td>
    <td><%= event.fecha %></td>
    <td><%= event.participantes %></td>
    <td><%= link_to 'Editar', edit_event_path(event) %></td>
    <td><%= link_to "Eliminar", event, method: :delete, data: { confirm: 'Esta seguro?' }%></td>


    </tr>
    <% end %>
  
  
</tbody>
</table>

app/views/events/new.html.erb
<div style=width:80%;margin:0 auto;>

    

<%=  render 'form', name:"Crear" %>

   </div>

app/views/events/show.html.erb
    <h3> <%= @Event.nombre %></h3>
    <p><%= @Event.lugar %></p>
    <p><%= @Event.fecha %></p>
    <p><%= @Event.participantes %></p>

    <br>

app/views/foundations/_form.html.erb
<div style=width:80%;margin:0 auto; class="container" >

<% name ||="Crear" %>
<h1> <%=name%> Fundacion </h1>

<% @Foundation.errors.full_messages.each do |error| %>
    <p><%= error %></p>
    <%end%>


<%= form_for(@Foundation) do |f| %>
<%= f.text_field :nombre, placeholder:"Nombre de la fundación" %>
<%= f.text_area :resumen, placeholder:"Resumen para Zona de Fundaciones" %>
<%= f.text_area :objeto, placeholder:"Objeto de la fundación, misión, visión" %>
<%= f.phone_field :telefono, placeholder:"telefono", autofocus: true, placeholder: 'xxx-xxx-xx' %>
<%= f.url_field :sitio_web, placeholder:"URL sitio web - Incluir HTTP" %>


<%= f.submit "Guardar" %>

    <%end%>

    </div>

app/views/foundations/edit.html.erb
<div style=width:80%;margin:0 auto;>

    

<%=  render 'form', name:"Editar" %>

   </div>

app/views/foundations/index.html.erb
<table class="striped">
<thead>
  <tr>
      <th>Nombre fundación</th>
      <th>Resumen</th>
      <th colspan="2" >Accion</th>
  </tr>
</thead>

<tbody>
  <tr>
  <% @Foundation.each do |fundacion| %>
    <td><%= fundacion.nombre %></td>
    <td><%= fundacion.resumen %></td>
    <td><%= link_to 'Editar', edit_foundation_path(fundacion) %></td>
    <td><%= link_to "Eliminar", fundacion, method: :delete, data: { confirm: 'Esta seguro?' }%></td>
    </tr>
    <% end %>
  
  
</tbody>
</table>


<div class="row">
<% @Foundation.each do |fundacion| %>
<div class="col s12 m6">
  <div class="card blue-grey darken-1">
    <div class="card-content white-text">
      <span class="card-title"><%= fundacion.nombre %></span>
      <p><%= fundacion.resumen %></p>
    </div>
    <div class="card-action">
      <a href="#">Ir a sitio web de la fundacion</a>
      <a class="waves-effect waves-light btn modal-trigger" href="#modal1">Modal</a>
      
    </div>
  </div>
</div>

<!-- Modal Structure -->
<div id="modal1" class="modal">
  <div class="modal-content">
    <h4><%= fundacion.nombre %></h4>
    <p><%= fundacion.resumen %></p>
  </div>
  <div class="modal-footer">
    <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">Agree</a>
  </div>
</div>
<% end %>







  <script src="../assets/welcome.js"></script>

app/views/foundations/new.html.erb
<div style=width:80%;margin:0 auto;>

    

<%=  render 'form', name:"Crear" %>

   </div>

app/views/foundations/show.html.erb
    <h3> <%= @Foundation.nombre %></h3>
    <p><%= @Foundation.resumen %></p>
    <p><%= @Foundation.objeto %></p>
    <p><%= @Foundation.telefono %></p>
    <p><%= @Foundation.sitio_web %></p>
    <br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fundaciones La Candelaria</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <style src="../assets/style.scss"></style>
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

 <!--Titulo-->
  <div class="navbar-fixed">
    <nav class="top-nav center" id="titulo">
      <div class="nav-wrapper">
          <h4>Fundaciones La Candelaria</h4>
          <h5>ALCALDÍA LOCAL LA CANDELARIA</h5>
      </div>
    </nav>  
  </div>
<!--Menu-->
  <div class="navbar-fixed">
  <% @Menu = Menu.all%>
    <nav>
      <ul class="tabs tabs-transparent">
      <!--Boton para el login-->
        <li class="tab"><a href="#" data-activates="slide-out" class="button-collapse"><i class="material-icons">menu</i></a></li>
        <% @Menu.each do |menu| %>
          <li class="tab"><a class="active" href="<%= menu.enlace %>"><%= menu.nombre %></a></li>
        <%end%>
      </ul>
    </nav>
  </div>





  <!--Login-->

  <ul id="slide-out" class="side-nav">
    <li><div class="user-view">
      <div class="background">
        <img src="../assets/imagen4.jpg">
      </div>
      <a href="#!user"><img class="circle" src="images/yuna.jpg"></a>
      <a href="#!name"><span class="white-text name">John Doe</span></a>
      <a href="#!email"><span class="white-text email">jdandturk@gmail.com</span></a>
    </div></li>

    
    <li>
    
    <ul class="collapsible">
    <li class="active">
      <div class="collapsible-header"><i class="material-icons">assignment_ind</i>Iniciar Sesion</div>
      <div class="collapsible-body">
          
      <div class="row">
      <form class="col s12">
        <div class="row">
          <div class="input-field col s12">
            <i class="material-icons Small prefix">account_circle</i>
            <input id="icon_prefix" type="email" class="validate" required>
            <label for="icon_prefix">Correo Eléctronico</label>
          </div>
          <div class="input-field col s12">
            <i class="material-icons Small prefix">phone</i>
            <input id="icon_telephone" type="password" class="validate" required>
            <label for="icon_telephone">Contraseña</label>
          </div>
          <div class="container s12 offset-2">
          <button class="btn waves-effect waves-light" type="submit" name="action">Enviar
            <i class="material-icons right">send</i>
          </button>
          </div>
        </div>
      </form>
  </div>
      
      
      
      
      </div>
    </li>

  </ul>
  
  </ul>





  <div class="container" style="width:70%;">        
      <%= yield %>
</div>


    <!--Footer-->

    <footer class="page-footer">
      <div class="container">
        <div class="row">
          <div class="col l4 s12 center">
            <img src="../assets/alcaldia.png">
          </div>


          <div class="col l6 offset-l2 s12 center">
            <h6 class="white-text">Contacto Alcaldía</h6>
            <ul>
              <li>Dirección: Carrera 5 No. 12C - 40 <br>
              Telefonos: (+57) 1 341 60 09, (+57) 1 341 02 61
              <br>Correo Institucional: Bogotá Te Escucha - Sistema Distrital de Quejas y Soluciones
              <br>Correo Notificaciones Judiciales: notificacionesjudiciales@gobiernobogota.gov.co
              <br>Horario: Lunes a Viernes de 7:00 a.m a 1:00 p.m. y de 2:00 p.m. a 4:30 p.m.
              <br>Ciudad: Bogotá - Colombia</li>
            </ul>
          </div>
        </div>
      </div>
    </footer>


  
    <script src="../assets/welcome.js"></script>
  </body>
</html>

app/views/menus/edit.html.erb
<div style=width:80%;margin:0 auto; class="container" >




<% @Menu.errors.full_messages.each do |error| %>
    <p><%= error %></p>
    <%end%>





<%= form_for(@Menu) do |f| %>
<%= f.text_field :nombre, placeholder:"Nombre Menu" %>
<%= f.text_field :enlace, placeholder:"URL" %>



<%= f.submit "Guardar" %>

    <%end%>

    </div>

app/views/menus/index.html.erb
<table class="striped">
<thead>
  <tr>
      <th>Nombre menu</th>
      <th>enlace</th>
      <th colspan="2" >Accion</th>
  </tr>
</thead>


<tbody>
  <tr>
  <% @Menu.each do |menu| %>
    <td><%= menu.nombre %></td>
    <td><%= menu.enlace %></td>
    <td><%= link_to 'Editar', edit_menu_path(menu) %></td>
    <td><%= link_to "Eliminar", menu, method: :delete, data: { confirm: 'Esta seguro?' }%></td>
    </tr>
    <% end %>
  
  
</tbody>
</table>

app/views/menus/new.html.erb
<div style=width:80%;margin:0 auto; class="container" >




<% @Menu.errors.full_messages.each do |error| %>
    <p><%= error %></p>
    <%end%>





<%= form_for(@Menu) do |f| %>
<%= f.text_field :nombre, placeholder:"Nombre Menu" %>
<%= f.text_field :enlace, placeholder:"URL" %>



<%= f.submit "Guardar" %>

    <%end%>

    </div>

app/views/menus/show.html.erb
    <h3> <%= @Menu.nombre %></h3>
    <p><%= @Menu.enlace %></p>

    <br>

rails

app/views/welcome/index.html.erb
<section class="row">
<div class="slider col s12">
    <ul class="slides">
      <li>
        <img src="../assets/imagen.jpg"> <!-- random image -->
        <div class="caption center-align">
          <h3 class="brown-text text-darken-2">La Candelaria</h3>
        </div>
      </li>
      <li>
        <img src="../assets/imagen1.jpg"> <!-- random image -->
        <div class="caption center-align">
          <h3>Plaza de Bolivar</h3>
        </div>
      </li>
      <li>
        <img src="../assets/imagen2.jpg"> <!-- random image -->
        <div class="caption center-align">
          <h3>Chorro de Quevedo</h3>
        </div>
      </li>
      <li>
        <img src="../assets/imagen3.jpg"> <!-- random image -->
        <div class="caption center-align">
          <h3>Teatro Municipal Jorge Eliecer Gaitan</h3>
        </div>
      </li>
    </ul>
  </div>
</section>

<script src="../assets/welcome.js"></script>